dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

networks:
  default: development
  mainnet-fork: #this is the mainnet-fork account from alchemy
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419" # this is from chainlink mainnet
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
  kovan:
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C" # this is for mock
    dai_usd_price_feed: "0x777A68032a88E5A84678A77Af2CD65A7b3c0775a"
